package activity11;

public class DivisionException extends Exception {
	/**
	 * Auto-generated by the Eclipse help
	 */
	private static final long serialVersionUID = 1L;

	public DivisionException() {
		super("Impossible to divide by zero");
	}
}
